on:
  workflow_call:
    inputs: 
      environment: 
        type: string
        required: true
      app_service_name:
        type: string
        required: true
      app_service_resource_group:
        type: string
        required: true
      healtcheck_path:
        type: string
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Build app
        uses: ./.github/actions/node-yarn

      - name: Make the azure app artifact
        id: make_artifact
        run: |
          zip -r app.zip .
          echo "artifact-path=$(realpath app.zip)" >> "$GITHUB_OUTPUT"
        shell: bash
      
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: app.zip
          path: ${{ steps.make_artifact.outputs.artifact-path }}

  deploy:
    name: Deploy App
    if: ${{ !github.event.act }}
    needs: [build]
    runs-on: self-hosted
    environment: ${{ inputs.environment }}-cd
    permissions:
      id-token: write
      contents: read
    env:
      ARM_USE_OIDC: true
      ARM_USE_AZUREAD: true
      ARM_STORAGE_USE_AZUREAD: true

    steps:
      - name: Download artifact
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: app.zip
        
      - name: Login to Azure
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: Deploy App to Staging Slot
        uses: azure/webapps-deploy@4bfb30bef2c330e36be280cb1e5726d0fac06233 # v2
        with:
          resource-group-name: ${{ inputs.app_service_resource_group }}
          app-name: ${{ inputs.app_service_name }}
          slot-name: staging
          package: app.zip

      - name: Check Staging Health
        run: curl --retry 5 --retry-max-time 120 -f 'https://${{ inputs.app_service_name }}-staging.azurewebsites.net${{ inputs.healtcheck_path }}'

      - name: Swap Staging and Production Slots
        run: az webapp deployment slot swap -g ${{ inputs.app_service_resource_group }} -n ${{ inputs.app_service_name }} --slot staging --target-slot production